FROM ghcr.io/open-webui/open-webui:main
ENV HOST=0.0.0.0 PORT=8080 DATA_DIR=/app/backend/data WEBUI_AUTH=True ENABLE_SIGNUP=True ENABLE_OLLAMA_API=False ENABLE_WEBSOCKET_SUPPORT=True WEBSOCKET_MANAGER=redis
EXPOSE 8080
